export const CONSTANTS = {
  LAYOUT_CONFIG: {
    SUPPORT: [
      {
        title: "Home",
        subtitle: "",
        name: "",
        path: "/support",
        public: true,
      },
      {
        title: "Login",
        subtitle: "",
        name: "Login",
        path: "/login",
        public: true,
      },
      {
        title: "Sign-Up",
        subtitle: "",
        name: "Signup",
        path: "/sign-up",
        public: true,
      },
    ],
    HEALTH: [
      {
        title: "Home",
        subtitle: "",
        name: "",
        path: "/health",
        public: true,
      },
      {
        title: "Login",
        subtitle: "",
        name: "Login",
        path: "/login",
        public: true,
      },
      {
        title: "Sign-Up",
        subtitle: "",
        name: "Signup",
        path: "/sign-up",
        public: true,
      },
    ],
    NEWS: [
      {
        title: "Home",
        subtitle: "",
        name: "",
        path: "/news",
        public: true,
      },
      {
        title: "Login",
        subtitle: "",
        name: "Login",
        path: "/login",
        public: true,
      },
      {
        title: "Sign-Up",
        subtitle: "",
        name: "Signup",
        path: "/sign-up",
        public: true,
      },
    ],
    VIDEOS: [
      {
        title: "Home",
        subtitle: "",
        name: "",
        path: "/videos",
        public: true,
      },
      {
        title: "Login",
        subtitle: "",
        name: "Login",
        path: "/login",
        public: true,
      },
      {
        title: "Sign-Up",
        subtitle: "",
        name: "Signup",
        path: "/sign-up",
        public: true,
      },
    ],
    LIFE_STYLE: [
      {
        title: "Home",
        subtitle: "",
        name: "",
        path: "/life-style",
        public: true,
      },
      {
        title: "Login",
        subtitle: "",
        name: "Login",
        path: "/login",
        public: true,
      },
      {
        title: "Sign-Up",
        subtitle: "",
        name: "Signup",
        path: "/sign-up",
        public: true,
      },
    ],
    MUSIC: [
      {
        title: "Home",
        subtitle: "",
        name: "",
        path: "/music",
        public: true,
      },
      {
        title: "Login",
        subtitle: "",
        name: "Login",
        path: "/login",
        public: true,
      },
      {
        title: "Sign-Up",
        subtitle: "",
        name: "Signup",
        path: "/sign-up",
        public: true,
      },
    ],
    WE: [
      {
        title: "Home",
        subtitle: "",
        name: "",
        path: "/we",
        public: true,
      },
      {
        title: "Login",
        subtitle: "",
        name: "Login",
        path: "/login",
        public: true,
      },
      {
        title: "Sign-Up",
        subtitle: "",
        name: "Signup",
        path: "/sign-up",
        public: true,
      },
    ],
    GAMES: [
      {
        title: "Home",
        subtitle: "",
        name: "",
        path: "/games",
        public: true,
      },
      {
        title: "Login",
        subtitle: "",
        name: "Login",
        path: "/login",
        public: true,
      },
      {
        title: "Sign-Up",
        subtitle: "",
        name: "Signup",
        path: "/sign-up",
        public: true,
      },
    ],
  },

  CARD_DUMMY_DATA: [
    {
      title: "Card Title 1",
      description: "This is a description for card 1.",
      imageUrl: "https://via.placeholder.com/300x200",
      link: "#",
    },
    {
      title: "Card Title 2",
      description: "This is a description for card 2.",
      imageUrl: "https://via.placeholder.com/300x200",
      link: "#",
    },
    {
      title: "Card Title 3",
      description: "This is a description for card 3.",
      imageUrl: "https://via.placeholder.com/300x200",
      link: "#",
    },
  ],

  APP_NAV_DATA: [
    {
      title: "Health",
      description: "This is a description for card 1.",
      imageUrl: "https://via.placeholder.com/300x200",
      path: "/health",
    },
    {
      title: "Life Style",
      description: "This is a description for card 1.",
      imageUrl: "https://via.placeholder.com/300x200",
      path: "/life-style",
    },
    {
      title: "Who we are",
      description: "This is a description for card 1.",
      imageUrl: "https://via.placeholder.com/300x200",
      path: "/we",
    },
    {
      title: "Support",
      description: "This is a description for card 1.",
      imageUrl: "https://via.placeholder.com/300x200",
      path: "support",
    },
    {
      title: "Videos",
      description: "This is a description for card 1.",
      imageUrl: "https://via.placeholder.com/300x200",
      path: "/videos",
    },
    {
      title: "Music",
      description: "This is a description for news page",
      imageUrl: "https://via.placeholder.com/300x200",
      path: "/music",
    },
    {
      title: "News",
      description: "This is a description for news page",
      imageUrl: "https://via.placeholder.com/300x200",
      path: "/news",
    },
    {
      title: "Chats",
      description: "This is a description for chats",
      imageUrl: "https://via.placeholder.com/300x200",
      path: "/chats",
    },
    {
      title: "GPT",
      description: "This is a description for card 1.",
      imageUrl: "https://via.placeholder.com/300x200",
      path: "/genarative.ai",
    },
  ],
};
