export const CONSTANTS = {
  LAYOUT_CONFIG: {
    SUPPORT: [
      {
        title: "Home",
        subtitle: "",
        name: "",
        path: "/support",
        public: true,
      },
      {
        title: "Login",
        subtitle: "",
        name: "Login",
        path: "/login",
        public: true,
      },
      {
        title: "Sign-Up",
        subtitle: "",
        name: "Signup",
        path: "/sign-up",
        public: true,
      },
    ],
    HEALTH: [
      {
        title: "Home",
        subtitle: "",
        name: "",
        path: "/health",
        public: true,
      },
      {
        title: "Login",
        subtitle: "",
        name: "Login",
        path: "/login",
        public: true,
      },
      {
        title: "Sign-Up",
        subtitle: "",
        name: "Signup",
        path: "/sign-up",
        public: true,
      },
    ],
    NEWS: [
      {
        title: "Home",
        subtitle: "",
        name: "",
        path: "/news",
        public: true,
      },
      {
        title: "Login",
        subtitle: "",
        name: "Login",
        path: "/login",
        public: true,
      },
      {
        title: "Sign-Up",
        subtitle: "",
        name: "Signup",
        path: "/sign-up",
        public: true,
      },
    ],
    VIDEOS: [
      {
        title: "Home",
        subtitle: "",
        name: "",
        path: "/videos",
        public: true,
      },
      {
        title: "Login",
        subtitle: "",
        name: "Login",
        path: "/login",
        public: true,
      },
      {
        title: "Sign-Up",
        subtitle: "",
        name: "Signup",
        path: "/sign-up",
        public: true,
      },
    ],
    LIFE_STYLE: [
      {
        title: "Home",
        subtitle: "",
        name: "",
        path: "/life-style",
        public: true,
      },
      {
        title: "Login",
        subtitle: "",
        name: "Login",
        path: "/login",
        public: true,
      },
      {
        title: "Sign-Up",
        subtitle: "",
        name: "Signup",
        path: "/sign-up",
        public: true,
      },
    ],
    MUSIC: [
      {
        title: "Home",
        subtitle: "",
        name: "",
        path: "/music",
        public: true,
      },
      {
        title: "Login",
        subtitle: "",
        name: "Login",
        path: "/login",
        public: true,
      },
      {
        title: "Sign-Up",
        subtitle: "",
        name: "Signup",
        path: "/sign-up",
        public: true,
      },
    ],
    WE: [
      {
        title: "Home",
        subtitle: "",
        name: "",
        path: "/we",
        public: true,
      },
      {
        title: "Login",
        subtitle: "",
        name: "Login",
        path: "/login",
        public: true,
      },
      {
        title: "Sign-Up",
        subtitle: "",
        name: "Signup",
        path: "/sign-up",
        public: true,
      },
    ],
    GAMES: [
      {
        title: "Home",
        subtitle: "",
        name: "",
        path: "/games",
        public: true,
      },
      {
        title: "Login",
        subtitle: "",
        name: "Login",
        path: "/login",
        public: true,
      },
      {
        title: "Sign-Up",
        subtitle: "",
        name: "Signup",
        path: "/sign-up",
        public: true,
      },
    ],
  },

  CARD_DUMMY_DATA: [
    {
      title: "Card Title 1",
      description: "This is a description for card 1.",
      imageUrl: "https://via.placeholder.com/300x200",
      link: "#",
    },
    {
      title: "Card Title 2",
      description: "This is a description for card 2.",
      imageUrl: "https://via.placeholder.com/300x200",
      link: "#",
    },
    {
      title: "Card Title 3",
      description: "This is a description for card 3.",
      imageUrl: "https://via.placeholder.com/300x200",
      link: "#",
    },
  ],

  APP_NAV_DATA: [
    {
      title: "Health",
      description: "This is a description for card 1.",
      imageUrl: "https://via.placeholder.com/300x200",
      path: "/health",
    },
    {
      title: "Life Style",
      description: "This is a description for card 1.",
      imageUrl: "https://via.placeholder.com/300x200",
      path: "/life-style",
    },
    {
      title: "Who we are",
      description: "This is a description for card 1.",
      imageUrl: "https://via.placeholder.com/300x200",
      path: "/we",
    },
    {
      title: "Support",
      description: "This is a description for card 1.",
      imageUrl: "https://via.placeholder.com/300x200",
      path: "support",
    },
    {
      title: "Videos",
      description: "This is a description for card 1.",
      imageUrl: "https://via.placeholder.com/300x200",
      path: "/videos",
    },
    {
      title: "Music",
      description: "This is a description for news page",
      imageUrl: "https://via.placeholder.com/300x200",
      path: "/music",
    },
    {
      title: "News",
      description: "This is a description for news page",
      imageUrl: "https://via.placeholder.com/300x200",
      path: "/news",
    },
    {
      title: "Chats",
      description: "This is a description for chats",
      imageUrl: "https://via.placeholder.com/300x200",
      path: "/chats",
    },
    {
      title: "GPT",
      description: "This is a description for card 1.",
      imageUrl: "https://via.placeholder.com/300x200",
      path: "/genarative.ai",
    },
  ],
  // SONGS: [
  //   {
  //     title: "Song 1",
  //     artist: "Artist 1",
  //     cover: "https://via.placeholder.com/300x200",
  //     audio: "https://example.com/audio1.mp3",
  //   },
  //   {
  //     title: "Song 2",
  //     artist: "Artist 2",
  //     cover: "https://via.placeholder.com/300x200",
  //     audio: "https://example.com/audio2.mp3",
  //   },
  //   {
  //     title: "Song 3",
  //     artist: "Artist 3",
  //     cover: "https://via.placeholder.com/300x200",
  //     audio: "https://example.com/audio3.mp3",
  //   },
  // ],

  // SONGS: [
  //   {
  //     title: "G.O.A.T.",
  //     artist: "Diljit Dosanjh",
  //     cover: "https://link.to/cover/goat.jpg",
  //     audio: "https://link.to/audio/goat.mp3",
  //   },
  //   {
  //     title: "Do You Know",
  //     artist: "Diljit Dosanjh",
  //     cover: "https://link.to/cover/doyouknow.jpg",
  //     audio: "https://link.to/audio/doyouknow.mp3",
  //   },
  //   {
  //     title: "5 Taara",
  //     artist: "Diljit Dosanjh",
  //     cover: "https://link.to/cover/5taara.jpg",
  //     audio: "https://link.to/audio/5taara.mp3",
  //   },
  //   {
  //     title: "Laembadgini",
  //     artist: "Diljit Dosanjh",
  //     cover: "https://link.to/cover/laembadgini.jpg",
  //     audio: "https://link.to/audio/laembadgini.mp3",
  //   },
  //   {
  //     title: "Patiala Peg",
  //     artist: "Diljit Dosanjh",
  //     cover: "https://link.to/cover/patialapeg.jpg",
  //     audio: "https://link.to/audio/patialapeg.mp3",
  //   },
  //   {
  //     title: "Raat Di Gedi",
  //     artist: "Diljit Dosanjh",
  //     cover: "https://link.to/cover/raatdigedi.jpg",
  //     audio: "https://link.to/audio/raatdigedi.mp3",
  //   },
  //   {
  //     title: "El Sueno",
  //     artist: "Diljit Dosanjh",
  //     cover: "https://link.to/cover/elsueno.jpg",
  //     audio: "https://link.to/audio/elsueno.mp3",
  //   },
  //   {
  //     title: "Jind Mahi",
  //     artist: "Diljit Dosanjh",
  //     cover: "https://link.to/cover/jindmahi.jpg",
  //     audio: "https://link.to/audio/jindmahi.mp3",
  //   },
  //   {
  //     title: "Ikk Kudi",
  //     artist: "Diljit Dosanjh",
  //     cover: "https://link.to/cover/ikkkudi.jpg",
  //     audio: "https://link.to/audio/ikkkudi.mp3",
  //   },
  //   {
  //     title: "Sauda Khara Khara",
  //     artist: "Diljit Dosanjh",
  //     cover: "https://link.to/cover/saudakharakhara.jpg",
  //     audio: "https://link.to/audio/saudakharakhara.mp3",
  //   },
  // ],
  SONGS: [
    {
      title: "G.O.A.T.",
      artist: "Diljit Dosanjh",
      cover: "https://via.placeholder.com/300x200?text=G.O.A.T.",
      audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    },
    {
      title: "Do You Know",
      artist: "Diljit Dosanjh",
      cover: "https://via.placeholder.com/300x200?text=Do+You+Know",
      audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    },
    {
      title: "5 Taara",
      artist: "Diljit Dosanjh",
      cover: "https://via.placeholder.com/300x200?text=5+Taara",
      audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    },
    {
      title: "Laembadgini",
      artist: "Diljit Dosanjh",
      cover: "https://via.placeholder.com/300x200?text=Laembadgini",
      audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    },
    {
      title: "Patiala Peg",
      artist: "Diljit Dosanjh",
      cover: "https://via.placeholder.com/300x200?text=Patiala+Peg",
      audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    },
    {
      title: "Raat Di Gedi",
      artist: "Diljit Dosanjh",
      cover: "https://via.placeholder.com/300x200?text=Raat+Di+Gedi",
      audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    },
    {
      title: "El Sueno",
      artist: "Diljit Dosanjh",
      cover: "https://via.placeholder.com/300x200?text=El+Sueno",
      audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    },
    {
      title: "Jind Mahi",
      artist: "Diljit Dosanjh",
      cover: "https://via.placeholder.com/300x200?text=Jind+Mahi",
      audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    },
    {
      title: "Ikk Kudi",
      artist: "Diljit Dosanjh",
      cover: "https://via.placeholder.com/300x200?text=Ikk+Kudi",
      audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    },
    {
      title: "Sauda Khara Khara",
      artist: "Diljit Dosanjh",
      cover: "https://via.placeholder.com/300x200?text=Sauda+Khara+Khara",
      audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    },
  ],
};
